// The five Dark Side of the Rainbow posters — text + imagery for each
// issue, lifted verbatim from the project's p5 sketch. Exposed on
// window.DSOTR_POSTERS for the feed UI kit.
window.DSOTR_POSTERS = [
  {
    name: "Suicide",
    thumb: "./assets/thumbs/head.png",
    image: "./assets/posters/head-cmy.png",
    imageDark: "./assets/posters/head-rgb.png",
    caption: "Suicidal ideation among LGBTQ+ youth. Tap to see how you can help.",
    stat: "39", unit: "%",
    problem: [
      { t: "of young LGBTQ+ members seriously " },
      { t: "considered attempting suicide", b: true },
      { t: " in the past year including 46% of transgender and nonbinary young people. LGBTQ+ youth of color reported higher rates than White peers." },
    ],
    cta: "You Can Help Them",
    lead: "LGBTQ+ youth who have at least",
    support: "1 Accepting\nAdult",
    stat2: "40", unit2: "%",
    closing: [{ t: "less likely", b: true }, { t: " to report a suicide attempt" }],
  },
  {
    name: "Bullying",
    thumb: "./assets/thumbs/fist.png",
    image: "./assets/posters/head-cmy.png",
    imageDark: "./assets/posters/head-rgb.png",
    caption: "Bullying and harassment at school. Tap to see how you can help.",
    stat: "83", unit: "%",
    problem: [
      { t: "of LGBTQ+ students " },
      { t: "experienced harassment or assault", b: true },
      { t: " at school based on who they are, including 32% who missed at least one day of school in the past month because they felt unsafe." },
    ],
    cta: "You Can Help Them",
    lead: "LGBTQ+ students who have at least",
    support: "1 Supportive\nEducator",
    stat2: "55", unit2: "%",
    closing: [{ t: "less likely", b: true }, { t: " to miss school out of fear" }],
  },
  {
    name: "Identity",
    thumb: "./assets/thumbs/eye.png",
    image: "./assets/posters/head-cmy.png",
    imageDark: "./assets/posters/head-rgb.png",
    caption: "Identity, pronouns and being seen. Tap to see how you can help.",
    stat: "60", unit: "%",
    problem: [
      { t: "of transgender and nonbinary teens say most people in their life " },
      { t: "don't respect their pronouns.", b: true },
      { t: " Being regularly misgendered is linked to higher rates of depression, anxiety, and suicide." },
    ],
    cta: "You Can Help Them",
    lead: "Trans and nonbinary youth who have",
    support: "1 Affirming\nFriend",
    stat2: "71", unit2: "%",
    closing: [{ t: "fewer symptoms", b: true }, { t: " of severe depression" }],
  },
  {
    name: "Safety",
    thumb: "./assets/thumbs/hand.png",
    image: "./assets/posters/head-cmy.png",
    imageDark: "./assets/posters/head-rgb.png",
    caption: "Access to mental health care. Tap to see how you can help.",
    stat: "50", unit: "%",
    problem: [
      { t: "of LGBTQ+ young people who wanted mental health care in the past year " },
      { t: "were not able to get it,", b: true },
      { t: " citing cost, fear of not being taken seriously, and not being out about who they are." },
    ],
    cta: "You Can Help Them",
    lead: "LGBTQ+ youth who have at least",
    support: "1 Inclusive\nSpace",
    stat2: "38", unit2: "%",
    closing: [{ t: "less likely", b: true }, { t: " to report a suicide attempt" }],
  },
  {
    name: "Politics",
    thumb: "./assets/thumbs/mouth.png",
    image: "./assets/posters/head-cmy.png",
    imageDark: "./assets/posters/head-rgb.png",
    caption: "Politics and LGBTQ+ youth. Tap to see how you can help.",
    stat: "90", unit: "%",
    problem: [
      { t: "of LGBTQ+ young people say their well-being was " },
      { t: "negatively impacted", b: true },
      { t: " by recent politics, including 39% whose families have thought about moving away because of anti-LGBTQ+ laws." },
    ],
    cta: "You Can Help Them",
    lead: "When affirming laws pass with",
    support: "1 Supportive\nVote",
    stat2: "14", unit2: "%",
    closing: [{ t: "fewer suicide attempts", b: true }, { t: " among LGBTQ+ students" }],
  },
];
